### ISSUE TITLE
Online Version Unaccessible for Long Time

### ISSUE THREAD

**Issue by zhuolix** [filannim/ManTIME#2]
So, I have tried to use the online version of the ManTIME, but it seems like my requests are always rejected. Any assistance is appreciated, thanks.

**Comment by filannim** [comment]
Hi SandyCreek,

the online version of the project was hosted on a machine maintained by The University of Manchester. It looks like the service is not up any more. Unfortunately, I've no control on it. You can use this repo to install it locally, server included.
